CREATE TABLE ERPL360.VENDEDOR(
   VENDEDOR VARCHAR(4) not null,
   CONJUNTO VARCHAR(10) not null,
   NOMBRRE VARCHAR(120) not null,
   EMPLEADO VARCHAR(50) null,
   COMISION DECIMAL(28,8) NULL,
   CTR_COMISION VARCHAR(25) NULL,
   CTA_COMISION VARCHAR(25) NULL,
   CORREO VARCHAR(249)NULL,
   ACTIVO VARCHAR(1) NOT NULL,
   TELEFONO VARCHAR(50) NULL,
   UpdatedBy varchar(25) not null,
   RecordDate datetime not null,
   CreatedBy varchar(25)not null,
   CreateDate datetime not null
)
ALTER TABLE ERPL360.VENDEDOR ADD PRIMARY KEY (VENDEDOR,CONJUNTO);
ALTER TABLE ERPL360.VENDEDOR
ADD CONSTRAINT FK_conjunto
FOREIGN KEY (CONJUNTO) REFERENCES ERPL360.CONJUNTO(CONJUNTO);

ALTER TABLE ERPL360.VENDEDOR ADD  CreatedBy varchar(25);
ALTER TABLE ERPL360.VENDEDOR ADD  UpdatedBy varchar(25);
ALTER TABLE ERPL360.VENDEDOR DROP COLUMN UpdatedBy ;

ALTER TABLE ERPL360.VENDEDOR
ADD CONSTRAINT FK_CreateBY
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE ERPL360.VENDEDOR
ADD CONSTRAINT FK_UpdatedBY
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

--- Pendiente de Aplicar las de contabilidad
-- Pendientes de aplicar