USE ERPL360
CREATE TABLE [ERPL360].[CONJUNTO](
	[CONJUNTO] [varchar](10) PRIMARY KEY,
	[NOMBRE] [varchar](100) NOT NULL,
	[DIREC1] [varchar](30) NOT NULL,
	[DIREC2] [varchar](30) NOT NULL,
	[TELEFONO] [varchar](30) NOT NULL,
	[LOGO] [varchar](100) NULL,
	[DOBLE_MONEDA] [varchar](1) NOT NULL,
	[DOBLE_CONTABILIDAD] [varchar](1) NOT NULL,
	[USA_LOTES] [varchar](1) NOT NULL,
	[USAR_CENTROS_COSTO] [varchar](1) NOT NULL,
	[CONSOLIDA] [varchar](1) NOT NULL,
	[CONSOLIDADORA] [varchar](10) NULL,
	[BD_CIA_CONSOLIDAD] [varchar](1) NULL,
	[CONTA_A_CONSOLID] [smallint] NULL,
	[MISMO_CUADRO_CTB] [varchar](1) NULL,
	[USUARIO_ULT_MOD] [varchar](25) NOT NULL,
	[FCH_HORA_ULT_MOD] [datetime] NOT NULL,
	[NOTAS] [text] NULL,
	[USA_UNIDADES] [varchar](1) NOT NULL,
    [UNIDAD_OMISION] [varchar](15) NULL,
	[MONEDA_CONSOLIDA] [varchar](1) NULL,
	[VERSION_BD] [varchar](8) NULL,
	[USUARIO_MODIF_BD] [varchar](40) NULL,
	[FCH_HORA_MODIF_BD] [datetime] NULL,
	[VERSION_INSTALAC] [varchar](8) NULL,
	[NIT] [varchar](20) NULL,
	[PAIS] [varchar](20) NULL,
	[GLN] [varchar](13) NULL,
	[UBICACION] [varchar](10) NULL,
	[IDIOMA] [varchar](10) NULL,
	[USA_SUCURSAL] [varchar](1) NULL,
	[MASCARA_SUCURSAL] [varchar](10) NULL,
	[DIRECCION_WEB1] [varchar](50) NULL,
	[DIRECCION_WEB2] [varchar](50) NULL,
	[NOMBRE_WEB1] [varchar](30) NULL,
	[NOMBRE_WEB2] [varchar](30) NULL,
	[DIRECCION_PAG_WEB] [varchar](50) NULL,
	[EMAIL_DOC_ELECTRONICO] [varchar](249) NULL,
	[PAIS_DIVISION] [varchar](4) NULL,
	[DIVISION_GEOGRAFICA1] [varchar](12) NULL,
	[DIVISION_GEOGRAFICA2] [varchar](12) NULL,
	[LOGO_CIA] [varbinary](max) NULL,
	[NUMERO_REGISTRO] [varchar](25) NULL,
	[DIREC3] [varchar](30) NULL,
	[COD_POSTAL] [varchar](10) NULL,
	[DIVISION_GEOGRAFICA3] [varchar](12) NULL,
	[DIVISION_GEOGRAFICA4] [varchar](12) NULL,
	[REGIMEN_FISCAL] [varchar](3) NULL

) 



ALTER TABLE [erpL360].[CONJUNTO] ADD  DEFAULT ('N') FOR [USA_SUCURSAL]
GO

ALTER TABLE [erpL360].[CONJUNTO] ADD  DEFAULT ('') FOR [MASCARA_SUCURSAL]
GO


ALTER TABLE [erpL360].[CONJUNTO]  WITH CHECK ADD  CONSTRAINT [USUAULTMOD] FOREIGN KEY([USUARIO_ULT_MOD])
REFERENCES [erpL360].[USUARIO] ([USUARIO])
GO

ALTER TABLE [erpadmin].[CONJUNTO] CHECK CONSTRAINT [USUAULTMOD]
GO



CREATE TABLE [ERPL360].[MODULO_INSTALADO](
	[CONJUNTO] [varchar](10) NOT NULL,
	[ACCION] [int] NOT NULL,
) 

ALTER TABLE [ERPL360].[MODULO_INSTALADO]
ADD CONSTRAINT [XPKMODULO_INSTALAD] PRIMARY KEY CLUSTERED 
(
	[CONJUNTO] ASC,
	[ACCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE [erpL360].[MODULO_INSTALADO]  WITH CHECK ADD  CONSTRAINT [CON_MI] FOREIGN KEY([CONJUNTO])
REFERENCES [erpadl360].[CONJUNTO] ([CONJUNTO])
ON DELETE CASCADE
GO

ALTER TABLE [erpL360].[MODULO_INSTALADO] CHECK CONSTRAINT [CON_MI]
GO

GO



CREATE TABLE [erpL360].[ACCION](
	[ACCION] [int] PRIMARY KEY,
	[NOMBREACCION] [varchar](40) NOT NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[NOMBRECONSTANTE] [varchar](18) NOT NULL,
	[ESMODULO] [varchar](1) NOT NULL,
	[TIPO] [varchar](1) NOT NULL,
	[SUBTIPO] [varchar](1) NOT NULL,
	[TABLA] [varchar](30) NULL,
	[INVOCACION] [varchar](1024) 
) 


CREATE TABLE [erpL360].[PARENTESCO](
	[ACCION] [int] NOT NULL,
	[PADRE] [int] NOT NULL,
	[NUMEROHERMANO] [smallint] NOT NULL
)

ALTER TABLE [ERPL360].[PARENTESCO]
ADD
	
 CONSTRAINT [XPKPARENTESCO] PRIMARY KEY NONCLUSTERED 
(
	[ACCION] ASC,
	[PADRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]





CREATE TABLE [ERPL360].[PRIVILEGIO_EX](
	[USUARIO] [varchar](25) NOT NULL,
	 [CONJUNTO] [varchar](10) NOT NULL,
	 [ACCION] [int] NOT NULL,
	 [ACTIVO] [varchar](1) NOT NULL
	 
)

ALTER TABLE [ERPL360].[PRIVILEGIO_EX]
ADD

 CONSTRAINT [XPKPRIVILEGIO] PRIMARY KEY NONCLUSTERED 
(
	[CONJUNTO] ASC,
	[USUARIO] ASC,
	[ACCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


ALTER TABLE [erpl360].[PRIVILEGIO_EX] ADD  DEFAULT ('S') FOR [ACTIVO]
GO



ALTER TABLE [erpl360].[PRIVILEGIO_EX]  WITH CHECK ADD  CONSTRAINT [CO_PRI] FOREIGN KEY([CONJUNTO])
REFERENCES [erpL360].[CONJUNTO] ([CONJUNTO])
ON DELETE CASCADE
GO

ALTER TABLE [erpl360].[PRIVILEGIO_EX] CHECK CONSTRAINT [CO_PRI]
GO

ALTER TABLE [erpl360].[PRIVILEGIO_EX]  WITH CHECK ADD  CONSTRAINT [USU_PRI] FOREIGN KEY([USUARIO])
REFERENCES [erpL360].[USUARIO] ([USUARIO])
ON DELETE CASCADE
GO

ALTER TABLE [erpl360].[PRIVILEGIO_EX] CHECK CONSTRAINT [USU_PRI]
GO





