CREATE SCHEMA DEMO
--Moneda
CREATE TABLE [DEMO].[MONEDA](
	[MONEDA] [varchar](4) NOT NULL,
	[NOMBRE] [varchar](40) NOT NULL,
	[CODIGO_ISO] [varchar](4) NULL,
	[RecordDate] [datetime] NOT NULL,
	[CreatedBy] [varchar](25) NOT NULL,
	[UpdatedBy] [varchar](25) NOT NULL,
	[CreateDate] [datetime] NOT NULL)
 
--Llave Primaria
ALTER TABLE DEMO.MONEDA ADD PRIMARY KEY (MONEDA );
--Laves Foraneas
ALTER TABLE DEMO.MONEDA
ADD CONSTRAINT FK_CreateBYMoneda
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.MONEDA
ADD CONSTRAINT FK_UpdatedBYMoneda
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);


--Unidad
CREATE TABLE [DEMO].[UNIDAD](
	[UNIDAD] [varchar](15) NOT NULL,
	[DESCRIPCION] [varchar](40) NULL,
	[RecordDate] [datetime] NOT NULL,
    [CreatedBy] [varchar](25) NOT NULL,
    [UpdatedBy] [varchar](25) NOT NULL,
   [CreateDate] [datetime] NOT NULL)

--llave primaria
ALTER TABLE DEMO.UNIDAD ADD PRIMARY KEY (UNIDAD);

--Llavez Foraneas
ALTER TABLE DEMO.UNIDAD
ADD CONSTRAINT FK_CreateBYUnidad
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);
ALTER TABLE DEMO.UNIDAD
ADD CONSTRAINT FK_UpdatedBYTipoCambio1
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);




--Tipo Cambio
CREATE TABLE [DEMO].[TIPO_CAMBIO](
	[TIPO_CAMBIO] [varchar](4) NOT NULL,
	[DESCRIPCION] [varchar](40) NOT NULL,
	[RecordDate] [datetime] NOT NULL,
    [CreatedBy] [varchar](25) NOT NULL,
    [UpdatedBy] [varchar](25) NOT NULL,
    [CreateDate] [datetime] NOT NULL)

--llave primaria
ALTER TABLE DEMO.TIPO_CAMBIO ADD PRIMARY KEY (TIPO_CAMBIO);
--Llavez Foraneas
ALTER TABLE DEMO.TIPO_CAMBIO
ADD CONSTRAINT FK_CreateBYTipoCambio
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);
ALTER TABLE DEMO.TIPO_CAMBIO
ADD CONSTRAINT FK_UpdatedBYTipoCambio
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);


-- Seccion Cuenta
CREATE TABLE [DEMO].[SECCION_CUENTA](
	[SECCION_CUENTA] [varchar](4) NOT NULL,
	[TIPO_SECCION] [varchar](1) NOT NULL,
	[DESCRIPCION] [varchar](40) NOT NULL,
	[ACUMULADO] [varchar](40) NULL,
	[SECUENCIA] [smallint] NOT NULL,
	[RecordDate] [datetime] NOT NULL,
    [CreatedBy] [varchar](25) NOT NULL,
    [UpdatedBy] [varchar](25) NOT NULL,
    [CreateDate] [datetime] NOT NULL)

--llave primaria
ALTER TABLE DEMO.SECCION_CUENTA ADD PRIMARY KEY (SECCION_CUENTA);

--Llavez Foraneas
ALTER TABLE DEMO.SECCION_CUENTA
ADD CONSTRAINT FK_CreateBYSeccionCuenta
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);
ALTER TABLE DEMO.SECCION_CUENTA
ADD CONSTRAINT FK_UpdatedBYSeccionCuenta
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);


--Cuenta Contable
CREATE TABLE [DEMO].[CUENTA_CONTABLE](
	[CUENTA_CONTABLE] [varchar](25) NOT NULL,
	[SECCION_CUENTA] [varchar](4) NULL,
	[UNIDAD] [varchar](15) NULL,
    [DESCRIPCION] [varchar](200) NOT NULL,
    [TIPO] [varchar](1) NOT NULL,
    [TIPO_DETALLADO] [varchar](1) NOT NULL,
    [TIPO_OAF] [varchar](1) NOT NULL,
    [SALDO_NORMAL] [varchar](1) NOT NULL,
    [CONVERSION] [varchar](1) NOT NULL,
    [TIPO_CAMBIO] [varchar](4) NOT NULL,
    [ACEPTA_DATOS] [varchar](1) NOT NULL,
    [CONSOLIDA] [varchar](1) NOT NULL,
    [USA_CENTRO_COSTO] [varchar](1) NOT NULL,
    [NOTAS] [text] NULL,
    [USUARIO] [varchar](25) NOT NULL,
    [FECHA_HORA] [datetime] NOT NULL,
    [USUARIO_ULT_MOD] [varchar](25) NOT NULL,
    [FCH_HORA_ULT_MOD] [datetime] NOT NULL,
    [ACEPTA_UNIDADES] [varchar](1) NOT NULL,
    [USO_RESTRINGIDO] [varchar](1) NOT NULL,
    [ORIGEN_CONVERSION] [varchar](1) NULL,
    [VALIDA_PRESUP_CR] [varchar](1) NOT NULL DEFAULT ('N') ,
    [CUENTA_IFRS] [varchar](25) NULL,
    [USA_CONTA_ELECTRO] [varchar](1) NOT NULL DEFAULT ('N'),
    [VERSION] [varchar](5) NOT NULL DEFAULT ('1.0'),
    [FECHA_INI_CE] [datetime] NULL,
    [FECHA_FIN_CE] [datetime] NULL,
    [COD_AGRUPADOR] [varchar](15) NULL,
    [DESC_COD_AGRUP] [varchar](60) NULL,
    [SUB_CTA_DE] [varchar](100) NULL,
    [DESC_SUB_CTA] [varchar](100) NULL,
    [NIVEL] [varchar](5) NULL,
    [MANEJA_TERCERO] [varchar](1) NOT NULL DEFAULT ('S') ,
    [DESCRIPCION_IFRS] [varchar](200) NULL,
	[RecordDate] [datetime] NOT NULL,
    [CreatedBy] [varchar](25) NOT NULL,
    [UpdatedBy] [varchar](25) NOT NULL,
    [CreateDate] [datetime] NOT NULL)
    
ALTER TABLE DEMO.CUENTA_CONTABLE ADD PRIMARY KEY (CUENTA_CONTABLE);


ALTER TABLE DEMO.CUENTA_CONTABLE
 WITH CHECK ADD CONSTRAINT FK_SECCIONcUENTAS
FOREIGN KEY (SECCION_CUENTA) REFERENCES DEMO.SECCION_CUENTA(SECCION_CUENTA);

ALTER TABLE [DEMO].[CUENTA_CONTABLE]  WITH CHECK ADD  CONSTRAINT [CTACTCMB] FOREIGN KEY(TIPO_CAMBIO)
REFERENCES [DEMO].[TIPO_CAMBIO] ([TIPO_CAMBIO])

ALTER TABLE [DEMO].[CUENTA_CONTABLE]  WITH CHECK ADD  CONSTRAINT [UNIDAD_CTA_CONTA] FOREIGN KEY([UNIDAD])
REFERENCES [DEMO].[UNIDAD] ([UNIDAD])


ALTER TABLE [DEMO].[CUENTA_CONTABLE]  WITH CHECK ADD  CONSTRAINT [USUOWNCUEN] FOREIGN KEY([USUARIO])
REFERENCES [ERPL360].[USUARIO] ([USUARIO])

ALTER TABLE [DEMO].[CUENTA_CONTABLE]  WITH CHECK ADD  CONSTRAINT [USUULTMOD] FOREIGN KEY([USUARIO_ULT_MOD])
REFERENCES [ERPL360].[USUARIO] ([USUARIO])


ALTER TABLE DEMO.CUENTA_CONTABLE
ADD CONSTRAINT FK_CreateBYCuentaContable
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.CUENTA_CONTABLE
ADD CONSTRAINT FK_UpdatedBYCuentaContable
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);



-- Centro Costo
CREATE TABLE [DEMO].[CENTRO_COSTO](
	[CENTRO_COSTO] [varchar](25) NOT NULL,
    [DESCRIPCION] [varchar](200) NOT NULL,
    [ACEPTA_DATOS] [varchar](1) NOT NULL,
    [TIPO] [varchar](1) NOT NULL,
    [RecordDate] [datetime] NOT NULL,
    [CreatedBy] [varchar](25) NOT NULL,
    [UpdatedBy] [varchar](25) NOT NULL,
    [CreateDate] [datetime] NOT NULL)
--llave primaria
ALTER TABLE DEMO.CENTRO_COSTO ADD PRIMARY KEY (CENTRO_COSTO);

--Llavez Foraneas
ALTER TABLE DEMO.CENTRO_COSTO
ADD CONSTRAINT FK_CreateBYCentroCosto
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);
ALTER TABLE DEMO.CENTRO_COSTO
ADD CONSTRAINT FK_UpdatedBYCentroCosto
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);



--CentroCuenta
CREATE TABLE [DEMO].[CENTRO_CUENTA](
	[CENTRO_COSTO] [varchar](25) NOT NULL,
	[CUENTA_CONTABLE] [varchar](25) NOT NULL,
	[ESTADO] [varchar](1) NOT NULL,
	[CENTRO_POZO] [varchar](25) NULL,
	[CUENTA_POZO] [varchar](25) NULL,
	[CENTRO_GASTO] [varchar](25) NULL,
	[CUENTA_GASTO] [varchar](25) NULL,
	[CENTRO_CONSOLIDA] [varchar](25) NULL,
	[CUENTA_CONSOLIDA] [varchar](25) NULL,
	[RecordDate] [datetime] NOT NULL,
    [CreatedBy] [varchar](25) NOT NULL,
    [UpdatedBy] [varchar](25) NOT NULL,
    [CreateDate] [datetime] NOT NULL)
	--llave primaria
ALTER TABLE DEMO.CENTRO_CUENTA ADD PRIMARY KEY (CENTRO_COSTO ASC,CUENTA_CONTABLE ASC);

--Llaves foreneas
ALTER TABLE [DEMO].[CENTRO_CUENTA]  WITH CHECK ADD  CONSTRAINT [CC_GASTO] FOREIGN KEY([CENTRO_GASTO], [CUENTA_GASTO])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[CENTRO_CUENTA]  WITH CHECK ADD  CONSTRAINT [CC_POZO] FOREIGN KEY([CENTRO_POZO], [CUENTA_POZO])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])
ALTER TABLE [DEMO].[CENTRO_CUENTA] CHECK CONSTRAINT [CC_POZO]

ALTER TABLE [DEMO].[CENTRO_CUENTA]  WITH CHECK ADD  CONSTRAINT [CNTCTACN] FOREIGN KEY([CENTRO_COSTO])
REFERENCES [DEMO].[CENTRO_COSTO] ([CENTRO_COSTO])
ON DELETE CASCADE
ALTER TABLE [DEMO].[CENTRO_CUENTA] CHECK CONSTRAINT [CNTCTACN]

ALTER TABLE [DEMO].[CENTRO_CUENTA]  WITH CHECK ADD  CONSTRAINT [CNTCTACT] FOREIGN KEY([CUENTA_CONTABLE])
REFERENCES [DEMO].[CUENTA_CONTABLE] ([CUENTA_CONTABLE])
ON DELETE CASCADE

ALTER TABLE [DEMO].[CENTRO_CUENTA] CHECK CONSTRAINT [CNTCTACT]

ALTER TABLE DEMO.CENTRO_CUENTA
ADD CONSTRAINT FK_CreateBYCentroCuenta
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.CENTRO_CUENTA
ADD CONSTRAINT FK_UpdatedBYCentroCuenta
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);





--Direccion
CREATE TABLE [DEMO].[DIRECCION](
	[DIRECCION] [varchar](10) NOT NULL,
	[DESCRIPCION] [varchar](40) NOT NULL,
	[NOMBRE_CAMPO_1] [varchar](60) NULL,
	[NOMBRE_CAMPO_2] [varchar](60) NULL,
	[NOMBRE_CAMPO_3] [varchar](60) NULL,
	[NOMBRE_CAMPO_4] [varchar](60) NULL,
	[NOMBRE_CAMPO_5] [varchar](60) NULL,
	[NOMBRE_CAMPO_6] [varchar](60) NULL,
	[NOMBRE_CAMPO_7] [varchar](60) NULL,
	[NOMBRE_CAMPO_8] [varchar](60) NULL,
	[NOMBRE_CAMPO_9] [varchar](60) NULL,
	[NOMBRE_CAMPO_10] [varchar](60) NULL,
	[USUARIO_CREACION] [varchar](25) NOT NULL,
 [FECHA_CREACION] [datetime] NOT NULL,
[USUARIO_ULT_MODIF] [varchar](25) NOT NULL,
 [FECHA_ULT_MODIF] [datetime] NOT NULL,
[RecordDate] [datetime] NOT NULL,
[CreatedBy] [varchar](25) NOT NULL,
[UpdatedBy] [varchar](25) NOT NULL,
[CreateDate] [datetime] NOT NULL)
ALTER TABLE DEMO.DIRECCION ADD PRIMARY KEY (DIRECCION);


ALTER TABLE DEMO.DIRECCION
ADD CONSTRAINT FK_CreateBYDireccion
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.DIRECCION
ADD CONSTRAINT FK_UpdatedBYDireccion
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.DIRECCION
ADD CONSTRAINT FK_UsuarioCreacionDireccion
FOREIGN KEY (USUARIO_CREACION) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.DIRECCION
ADD CONSTRAINT FK_UsuarioModficDireccion
FOREIGN KEY (USUARIO_ULT_MODIF) REFERENCES ERPL360.USUARIO(USUARIO);


--Pais
CREATE TABLE [DEMO].[PAIS](
	[PAIS] [varchar](4) NOT NULL,
	[DIRECCION] [varchar](10) NOT NULL,
	[NOMBRE] [varchar](40) NOT NULL,
	[CTR_VENTAS] [varchar](25) NULL,
	[CTA_VENTAS] [varchar](25) NULL,
	[CTR_DESC_GRAL] [varchar](25) NULL,
	[CTA_DESC_GRAL] [varchar](25) NULL,
	[CTR_COST_VENT] [varchar](25) NULL,
	[CTA_COST_VENT] [varchar](25) NULL,
	[CTR_DESC_LIN] [varchar](25) NULL,
	[CTA_DESC_LIN] [varchar](25) NULL,
	[CTR_COST_LIN] [varchar](25) NULL,
	[CTA_COST_LIN] [varchar](25) NULL,
	[CTR_GAST_COM] [varchar](25) NULL,
	[CTA_GAST_COM] [varchar](25) NULL,
	[CTR_CONTADO] [varchar](25) NULL,
	[CTA_CONTADO] [varchar](25) NULL,
	[CTR_CXC] [varchar](25) NULL,
	[CTA_CXC] [varchar](25) NULL,
	[CTR_LXC] [varchar](25) NULL,
	[CTA_LXC] [varchar](25) NULL,
	[CTR_PRONTO_PAG_CXC] [varchar](25) NULL,
	[CTA_PRONTO_PAG_CXC] [varchar](25) NULL,
	[CTR_INT_MORA_CXC] [varchar](25) NULL,
	[CTA_INT_MORA_CXC] [varchar](25) NULL,
	[CTR_RECIBOS_CXC] [varchar](25) NULL,
	[CTA_RECIBOS_CXC] [varchar](25) NULL,
	[CTR_DEBITO_CXC] [varchar](25) NULL,
	[CTA_DEBITO_CXC] [varchar](25) NULL,
	[CTR_CREDITO_CXC] [varchar](25) NULL,
	[CTA_CREDITO_CXC] [varchar](25) NULL,
	[CTR_IMPUESTO1_CXC] [varchar](25) NULL,
	[CTA_IMPUESTO1_CXC] [varchar](25) NULL,
	[CTR_IMPUESTO2_CXC] [varchar](25) NULL,
	[CTA_IMPUESTO2_CXC] [varchar](25) NULL,
	[CTR_RUBRO1_CXC] [varchar](25) NULL,
	[CTA_RUBRO1_CXC] [varchar](25) NULL,
	[CTR_RUBRO2_CXC] [varchar](25) NULL,
	[CTA_RUBRO2_CXC] [varchar](25) NULL,
	[CTR_ANTICIPO_CXC] [varchar](25) NULL,
	[CTA_ANTICIPO_CXC] [varchar](25) NULL,
	[CTR_LXP] [varchar](25) NULL,
	[CTA_LXP] [varchar](25) NULL,
	[CTR_CREDITO_CXP] [varchar](25) NULL,
	[CTA_CREDITO_CXP] [varchar](25) NULL,
	[CTR_DEBITO_CXP] [varchar](25) NULL,
	[CTA_DEBITO_CXP] [varchar](25) NULL,
	[CTR_CXP] [varchar](25) NULL,
	[CTA_CXP] [varchar](25) NULL,
	[CTR_PRONTO_PAG_CXP] [varchar](25) NULL,
	[CTA_PRONTO_PAG_CXP] [varchar](25) NULL,
	[CTR_COMISION_CXP] [varchar](25) NULL,
	[CTA_COMISION_CXP] [varchar](25) NULL,
	[CTR_IMPUESTO1_CXP] [varchar](25) NULL,
	[CTA_IMPUESTO1_CXP] [varchar](25) NULL,
	[CTR_IMPUESTO2_CXP] [varchar](25) NULL,
	[CTA_IMPUESTO2_CXP] [varchar](25) NULL,
	[CTR_RUBRO1_CXP] [varchar](25) NULL,
	[CTA_RUBRO1_CXP] [varchar](25) NULL,
	[CTR_RUBRO2_CXP] [varchar](25) NULL,
	[CTA_RUBRO2_CXP] [varchar](25) NULL,
	[CTR_ANTICIPO_CXP] [varchar](25) NULL,
	[CTA_ANTICIPO_CXP] [varchar](25) NULL,
	[CTR_DESC_BONIF] [varchar](25) NULL,
	[CTA_DESC_BONIF] [varchar](25) NULL,
	[CTR_DEV_VENTAS] [varchar](25) NULL,
	[CTA_DEV_VENTAS] [varchar](25) NULL,
	[CTR_INT_CORRIENTE] [varchar](25) NULL,
	[CTA_INT_CORRIENTE] [varchar](25) NULL,
	[CODIGO_ISO] [varchar](4) NULL,
	[ETIQUETA_DIV_GEO1] [varchar](20) NULL,
	[ETIQUETA_DIV_GEO2] [varchar](20) NULL,
	[MONEDA] [varchar](4) NULL,
	[CTR_VENTAS_EXEN] [varchar](25) NULL,
	[CTA_VENTAS_EXEN] [varchar](25) NULL,
	[CTR_AJUSTE_REDONDEO] [varchar](25) NULL,
	[CTA_AJUSTE_REDONDEO] [varchar](25) NULL,
	[ETIQUETA_DIV_GEO3] [varchar](20) NULL,
	[ETIQUETA_DIV_GEO4] [varchar](20) NULL,
	[U_PAIS] [varchar](4) NULL,
	[RecordDate] [datetime] NOT NULL,
	[CreatedBy] [varchar](25) NOT NULL,
	[UpdatedBy] [varchar](25) NOT NULL,
	[CreateDate] [datetime] NOT NULL)

--Llave Primaria
ALTER TABLE DEMO.PAIS ADD PRIMARY KEY (PAIS );
--Laves Foraneas
ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [CCDESCBONIFPAIS] FOREIGN KEY([CTR_DESC_BONIF], [CTA_DESC_BONIF])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [CTAAJUSREDONDEOPAIS] FOREIGN KEY([CTR_AJUSTE_REDONDEO], [CTA_AJUSTE_REDONDEO])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [CTAVENTEXENPAIS] FOREIGN KEY([CTR_VENTAS_EXEN], [CTA_VENTAS_EXEN])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAANTCC] FOREIGN KEY([CTR_ANTICIPO_CXP], [CTA_ANTICIPO_CXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAANTCXCCC] FOREIGN KEY([CTR_ANTICIPO_CXC], [CTA_ANTICIPO_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PACCXCCC] FOREIGN KEY([CTR_CREDITO_CXC], [CTA_CREDITO_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PACCXPCC] FOREIGN KEY([CTR_CREDITO_CXP], [CTA_CREDITO_CXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PACLINCC] FOREIGN KEY([CTR_COST_LIN], [CTA_COST_LIN])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PACOCPCC] FOREIGN KEY([CTR_COMISION_CXP], [CTA_COMISION_CXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PACONTCC] FOREIGN KEY([CTR_CONTADO], [CTA_CONTADO])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PACVENCC] FOREIGN KEY([CTR_COST_VENT], [CTA_COST_VENT])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PACXCCC] FOREIGN KEY([CTR_CXC], [CTA_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PACXPCC] FOREIGN KEY([CTR_CXP], [CTA_CXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PADCXCCC] FOREIGN KEY([CTR_DEBITO_CXC], [CTA_DEBITO_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PADCXPCC] FOREIGN KEY([CTR_DEBITO_CXP], [CTA_DEBITO_CXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PADGRLCC] FOREIGN KEY([CTR_DESC_GRAL], [CTA_DESC_GRAL])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PADLINCC] FOREIGN KEY([CTR_DESC_LIN], [CTA_DESC_LIN])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAGCOMCC] FOREIGN KEY([CTR_GAST_COM], [CTA_GAST_COM])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAIMP1CC] FOREIGN KEY([CTR_IMPUESTO1_CXP], [CTA_IMPUESTO1_CXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAIMP1CXCCC] FOREIGN KEY([CTR_IMPUESTO1_CXC], [CTA_IMPUESTO1_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAIMP2CC] FOREIGN KEY([CTR_IMPUESTO2_CXP], [CTA_IMPUESTO2_CXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAIMP2CXCCC] FOREIGN KEY([CTR_IMPUESTO2_CXC], [CTA_IMPUESTO2_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAINTCTECC] FOREIGN KEY([CTR_INT_CORRIENTE], [CTA_INT_CORRIENTE])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAINTMCC] FOREIGN KEY([CTR_INT_MORA_CXC], [CTA_INT_MORA_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAISDIR] FOREIGN KEY([DIRECCION])
REFERENCES [DEMO].[DIRECCION] ([DIRECCION])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAISDVCTRCTA] FOREIGN KEY([CTR_DEV_VENTAS], [CTA_DEV_VENTAS])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PALXCCC] FOREIGN KEY([CTR_LXC], [CTA_LXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PALXPCC] FOREIGN KEY([CTR_LXP], [CTA_LXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAPPCCCC] FOREIGN KEY([CTR_PRONTO_PAG_CXC], [CTA_PRONTO_PAG_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAPPCPCC] FOREIGN KEY([CTR_PRONTO_PAG_CXP], [CTA_PRONTO_PAG_CXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PARCXCCC] FOREIGN KEY([CTR_RECIBOS_CXC], [CTA_RECIBOS_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PARUB1CC] FOREIGN KEY([CTR_RUBRO1_CXP], [CTA_RUBRO1_CXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PARUB1CXCCC] FOREIGN KEY([CTR_RUBRO1_CXC], [CTA_RUBRO1_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PARUB2CC] FOREIGN KEY([CTR_RUBRO2_CXP], [CTA_RUBRO2_CXP])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PARUB2CXCCC] FOREIGN KEY([CTR_RUBRO2_CXC], [CTA_RUBRO2_CXC])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE [DEMO].[PAIS]  WITH CHECK ADD  CONSTRAINT [PAVENTCC] FOREIGN KEY([CTR_VENTAS], [CTA_VENTAS])
REFERENCES [DEMO].[CENTRO_CUENTA] ([CENTRO_COSTO], [CUENTA_CONTABLE])

ALTER TABLE DEMO.PAIS
ADD CONSTRAINT FK_CreateBYPais
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.PAIS
ADD CONSTRAINT FK_UpdatedBYPais
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);


--Vendedor

CREATE TABLE DEMO.VENDEDOR(
   VENDEDOR VARCHAR(4) not null,
   NOMBRE VARCHAR(120) not null,
   EMPLEADO VARCHAR(50) null,
   COMISION DECIMAL(28,8) NULL,
   CTR_COMISION VARCHAR(25) NULL,
   CTA_COMISION VARCHAR(25) NULL,
   CORREO VARCHAR(249)NULL,
   ACTIVO VARCHAR(1) NOT NULL,
   TELEFONO VARCHAR(50) NULL,
   UpdatedBy varchar(25) not null,
   RecordDate datetime not null,
   CreatedBy varchar(25)not null,
   CreateDate datetime not null
)
--Indicie vendedor conjunto
ALTER TABLE DEMO.VENDEDOR ADD PRIMARY KEY (VENDEDOR);
--Llavez Foraneas
ALTER TABLE DEMO.VENDEDOR
ADD CONSTRAINT FK_CreateBYVendedor
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);
ALTER TABLE DEMO.VENDEDOR
ADD CONSTRAINT FK_UpdatedBYVendedor
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);



--- Pendiente de Aplicar las de contabilidad
-- Pendientes de aplicar

--COBRADOR
CREATE TABLE DEMO.COBRADOR(
   COBRADOR VARCHAR(4) not null,
   NOMBRE VARCHAR(120) not null,
   EMPLEADO VARCHAR(50) null,
   COMISION DECIMAL(28,8) NULL,
   CTR_COMISION VARCHAR(25) NULL,
   CTA_COMISION VARCHAR(25) NULL,
   CORREO VARCHAR(249)NULL,
   ACTIVO VARCHAR(1) NOT NULL,
   TELEFONO VARCHAR(50) NULL,
   UpdatedBy varchar(25) not null,
   RecordDate datetime not null,
   CreatedBy varchar(25)not null,
   CreateDate datetime not null
);

--Indicie COBRADOR conjunto
ALTER TABLE DEMO.COBRADOR ADD PRIMARY KEY (COBRADOR);
--Llavez Foraneas
ALTER TABLE DEMO.COBRADOR ADD CONSTRAINT FK_CreateBYCobrador
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);
ALTER TABLE DEMO.COBRADOR ADD CONSTRAINT FK_UpdatedBYCobrador
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

--- Pendiente de Aplicar las de contabilidad
-- Pendientes de aplicar


--ZONA
CREATE TABLE [DEMO].[ZONA](
	[ZONA] [varchar](4) NOT NULL,
	[NOMBRE] [varchar](40) NOT NULL,
	[RecordDate] [datetime] NOT NULL,
	[CreatedBy] [varchar](25) NOT NULL,
	[UpdatedBy] [varchar](25) NOT NULL,
	[CreateDate] [datetime] NOT NULL)
 
--Llave Primaria
ALTER TABLE DEMO.ZONA ADD PRIMARY KEY (ZONA);
--Laves Foraneas
ALTER TABLE DEMO.ZONA
ADD CONSTRAINT FK_CreateBYZONA
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.ZONA
ADD CONSTRAINT FK_UpdatedBYZona
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);



--RUTA
CREATE TABLE [DEMO].[RUTA](
	[RUTA] [varchar](4) NOT NULL,
	[NOMBRE] [varchar](40) NOT NULL,
	[RecordDate] [datetime] NOT NULL,
	[CreatedBy] [varchar](30) NOT NULL,
	[UpdatedBy] [varchar](30) NOT NULL,
	[CreateDate] [datetime] NOT NULL)
--Llave Primaria
ALTER TABLE DEMO.RUTA ADD PRIMARY KEY (RUTA );
--Laves Foraneas
ALTER TABLE DEMO.ZONA
ADD CONSTRAINT FK_CreateBYZONA
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.ZONA
ADD CONSTRAINT FK_UpdatedBYZona
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);
 

 --CONSECUTIVO_CI
 CREATE TABLE [DEMO].[CONSECUTIVO_CI](
	[CONSECUTIVO] [varchar](10) NOT NULL,
	[ULTIMO_USUARIO] [varchar](25) NOT NULL,
	[DESCRIPCION] [varchar](40) NOT NULL,
	[MASCARA] [varchar](50) NOT NULL,
	[SIGUIENTE_CONSEC] [varchar](50) NOT NULL,
	[EDITABLE] [varchar](1) NOT NULL,
	[MULTIPLES_TRANS] [varchar](1) NOT NULL,
	[FORMATO_IMP] [varchar](254) NULL,
	[ULT_FECHA_HORA] [datetime] NOT NULL,
	[TODAS_TRANS] [varchar](1) NOT NULL,
	[TIPO] [varchar](4) NOT NULL,
	[RecordDate] [datetime] NOT NULL,
	[CreatedBy] [varchar](25) NOT NULL,
	[UpdatedBy] [varchar](25) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[USA_TRASLADO] [varchar](1) NOT NULL,
	[EMAIL_CFDI] [varchar](254) NULL)

ALTER TABLE DEMO.CONSECUTIVO_CI ADD PRIMARY KEY (CONSECUTIVO );
 
 ALTER TABLE DEMO.CONSECUTIVO_CI
ADD CONSTRAINT FK_CreateBYCONSECUTIVOCI
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.CONSECUTIVO_CI
ADD CONSTRAINT FK_UpdatedBYCONSECUTIVO_CI
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE [DEMO].[CONSECUTIVO_CI] ADD  DEFAULT ('N') FOR [USA_TRASLADO]
GO

ALTER TABLE [DEMO].[CONSECUTIVO_CI]  WITH CHECK ADD  CONSTRAINT [CONSUSR] FOREIGN KEY([ULTIMO_USUARIO])
REFERENCES [ERPL360].[USUARIO] ([USUARIO])
GO
ALTER TABLE [DEMO].[CONSECUTIVO_CI] CHECK CONSTRAINT [CONSUSR]



--BODEGA
CREATE TABLE [DEMO].[BODEGA](
	[BODEGA] [varchar](4) NOT NULL,
	[NOMBRE] [varchar](40) NOT NULL,
	[TIPO] [varchar](1) NOT NULL,
	[TELEFONO] [varchar](15) NOT NULL,
	[DIRECCION] [varchar](120) NULL,
	[CONSEC_TRASLADOS] [varchar](10) NULL,
	[RecordDate] [datetime] NOT NULL,
	[CreatedBy] [varchar](25) NOT NULL,
	[UpdatedBy] [varchar](25) NOT NULL,
	[CreateDate] [datetime] NOT NULL)
 

 ALTER TABLE DEMO.BODEGA ADD PRIMARY KEY (BODEGA );


 ALTER TABLE DEMO.BODEGA
ADD CONSTRAINT FK_CreateBYBODEGA
FOREIGN KEY (CreatedBy) REFERENCES ERPL360.USUARIO(USUARIO);

ALTER TABLE DEMO.BODEGA
ADD CONSTRAINT FK_UpdatedBYBODEGA
FOREIGN KEY (UpdatedBy) REFERENCES ERPL360.USUARIO(USUARIO);


ALTER TABLE [DEMO].[BODEGA]  WITH CHECK ADD  CONSTRAINT [BODECONSECI] FOREIGN KEY([CONSEC_TRASLADOS])
REFERENCES [DEMO].[CONSECUTIVO_CI] ([CONSECUTIVO])
GO

ALTER TABLE [DEMO].[BODEGA] CHECK CONSTRAINT [BODECONSECI]
GO


